#ifndef QTESTLIBPLUGIN_GLOBAL_H
#define QTESTLIBPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(QTESTLIBPLUGIN_LIBRARY)
#  define QTESTLIBPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTESTLIBPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTESTLIBPLUGIN_GLOBAL_H

